export const ActionTypes = {
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT",
  CREATE_STREAM: "CREATE_STREAM",
  FETCH_STREAMS: "FETCH_STREAMS",
  EDIT_STREAM: "EDIT_STREAM",
  SHOW_STREAM: "SHOW_STREAM",
  DELETE_STREAM: "DELETE_STREAM"
};